{
    'name': 'LiteAPI Booking',
    'version': '17.0.1.0.0',
    'summary': 'Foundation & Safety Layer for LiteAPI Integration',
    'description': """LiteAPI Booking Module""",
    'author': 'Antigravity',
    'category': 'Connector',
    'depends': ['base', 'website', 'sale', 'portal'],
    'data': [
        'security/ir.model.access.csv',
        'data/system_parameters.xml',
        'data/makkah_madinah.xml',
        'data/demo_hotels.xml',
        'data/cron.xml',
        'views/city_views.xml',
        'views/hotel_views.xml',
        'views/search_template.xml',
        'views/log_views.xml',
        'views/booking_views.xml',
        'views/reporting_views.xml',
        'views/portal_templates.xml',
        'views/menus.xml',
        'wizard/refund_wizard_view.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}